### PR TITLE
feat(build): use the tsup to build the project

### PR DESCRIPTION
**Pull request by AyAyEm**
### What did you fix? 

- Change how the build is done, by using [tsup](https://www.npmjs.com/package/tsup) for that job.
- Fix validate script. Which wasn't doing what was intended (to check if the project would build successfully)

---

### Reproduction steps

---

### Considerations
- Does this contain a new dependency? **[Yes]**
- Does this introduce opinionated data formatting or manual data entry? **[No]**
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[No]**
- Have I run the linter? **[Yes]**
- Is is a bug fix, feature request, or enhancement? **[Enhancement]**

BREAKING CHANGE:  bundle files with tsup

By bundling the files we aggregate build output files together, so some files that were accessible isn't anymore

### CODE REVIEW

**Comment by AyAyEm** [comment]
One thing to note: in the dist folder there's two js files Build and index. Build includes everything that index has, making it redundant in the developer environment but not in the npm package.

Edit: Four files now, in the npm package index.js and index.mjs would be redundant.

**Comment by TobiTenno** [comment]
i think this'd have to be a Breaking Change

**Comment by AyAyEm** [comment]
> i think this'd have to be a Breaking Change

Why?

**Comment by TobiTenno** [comment]
you're removing files from the public api, so that'd break code without those changes. all it is is a different version bump.

**Comment by AyAyEm** [comment]
I see your point but, the correct way to use the library wouldn't be through the index file? Anyway it should be fine to up a major.

**Comment by TobiTenno** [comment]
> I see your point but, the correct way to use the library wouldn't be through the index file? Anyway it should be fine to up a major.

no argument that it _should_ be used through the index file, but it was possible before, and now we're making it impossible, which is a no-no for passive minor changes

**Comment by AyAyEm** [comment]
@Soundofdarkness if possible i would like your opinion about this PR

**Review by TobiTenno — APPROVED** [review]

**Pull request merged**
